module.exports = {
  env: {
    NEXT_PUBLIC_FROM_CONFIG: 'NEXT_PUBLIC_FROM_CONFIG',
    FROM_CONFIG: 'FROM_CONFIG',
    NAME_CLASH_RUNTIME_VS_CONFIG: 'FROM_CONFIG',
    NAME_CLASH_RUNTIME_VS_CONFIG_VS_DOTFILE: 'FROM_CONFIG',
  },
};
